### ISSUE TITLE
User can see introduction page with the logo and get status button

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/ajax-project#2]
## 📐 Plan
Once user presses the Get Status Button, it will take the user to Home page (if car has been selected), if not will take them directly to "Find My Car" page.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/69870979/102282284-360a2700-3ee5-11eb-9e7a-2b310e89551a.png)

## ✅ Task List
- [x] Create a container to wrap the header, logo, and the button.
- [x] Set width and height using @Media based on the width and height of an iPhone 8. (375px X 667px)
- [x] Use psuedo class to give the button an animation effect.
- [x] Use CSS property to align the 3 elements in column form.
- [x] Create an AddEventListener on the button Check Status. 
- [x] If click occurs, class hidden will be applied to the div of the introduction page. 
- [x] Check to see if there any unnecessary CSS styling or items. 
- [x] Check to see if there are any bugs.
